In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle

In [2]:
df = pd.read_csv("C:/Users/ameen/Desktop/project/Employee_Attrition.csv.csv")
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,24,0,2,1242,1,3,3,0,1,1231,...,4,80,2,8,3,3,4,3,5,7
1,32,0,2,530,1,29,1,1,1,1101,...,4,80,1,6,3,3,1,2,10,1
2,39,0,2,1333,2,7,3,5,1,813,...,3,80,2,15,5,2,4,4,0,2
3,50,0,2,664,1,1,4,1,1,1683,...,1,80,2,5,3,3,3,7,0,2
4,48,0,2,667,1,1,1,1,1,1447,...,4,80,1,3,2,2,5,2,2,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,42,1,2,147,1,10,3,3,1,350,...,4,80,1,6,4,2,1,9,0,3
9996,29,0,1,855,2,5,2,1,1,1572,...,3,80,0,33,2,2,20,2,2,3
9997,42,0,2,809,2,1,1,2,1,254,...,4,80,1,7,6,3,17,2,7,3
9998,44,0,2,1050,1,2,5,3,1,133,...,2,80,1,8,3,2,3,3,15,4
9999,51,0,2,1217,2,1,4,3,1,584,...,4,80,1,7,4,3,13,0,0,4

In [3]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,24,0,2,1242,1,3,3,0,1,1231,...,4,80,2,8,3,3,4,3,5,7
1,32,0,2,530,1,29,1,1,1,1101,...,4,80,1,6,3,3,1,2,10,1
2,39,0,2,1333,2,7,3,5,1,813,...,3,80,2,15,5,2,4,4,0,2
3,50,0,2,664,1,1,4,1,1,1683,...,1,80,2,5,3,3,3,7,0,2
4,48,0,2,667,1,1,1,1,1,1447,...,4,80,1,3,2,2,5,2,2,13

In [4]:
df.tail()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
9995,42,1,2,147,1,10,3,3,1,350,...,4,80,1,6,4,2,1,9,0,3
9996,29,0,1,855,2,5,2,1,1,1572,...,3,80,0,33,2,2,20,2,2,3
9997,42,0,2,809,2,1,1,2,1,254,...,4,80,1,7,6,3,17,2,7,3
9998,44,0,2,1050,1,2,5,3,1,133,...,2,80,1,8,3,2,3,3,15,4
9999,51,0,2,1217,2,1,4,3,1,584,...,4,80,1,7,4,3,13,0,0,4

In [5]:
df.shape

(10000, 35)

In [6]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [7]:
df.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [8]:
y = df["Attrition"]
X = df.drop("Attrition", axis=1)
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,24,0,2,1242,1,3,3,0,1,1231,...,4,80,2,8,3,3,4,3,5,7
1,32,0,2,530,1,29,1,1,1,1101,...,4,80,1,6,3,3,1,2,10,1
2,39,0,2,1333,2,7,3,5,1,813,...,3,80,2,15,5,2,4,4,0,2
3,50,0,2,664,1,1,4,1,1,1683,...,1,80,2,5,3,3,3,7,0,2
4,48,0,2,667,1,1,1,1,1,1447,...,4,80,1,3,2,2,5,2,2,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,42,1,2,147,1,10,3,3,1,350,...,4,80,1,6,4,2,1,9,0,3
9996,29,0,1,855,2,5,2,1,1,1572,...,3,80,0,33,2,2,20,2,2,3
9997,42,0,2,809,2,1,1,2,1,254,...,4,80,1,7,6,3,17,2,7,3
9998,44,0,2,1050,1,2,5,3,1,133,...,2,80,1,8,3,2,3,3,15,4
9999,51,0,2,1217,2,1,4,3,1,584,...,4,80,1,7,4,3,13,0,0,4

In [9]:
label_encoders = {}

for column in X.columns:
    if X[column].dtype == 'object':
        le = LabelEncoder()
        X[column] = le.fit_transform(X[column])
        label_encoders[column] = le

In [10]:
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
nb_model=GaussianNB()
nb_model.fit(X_train,y_train)

GaussianNB()

In [13]:
y_pred=nb_model.predict(X_test)

In [14]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8495

Confusion Matrix:
 [[1699    0]
 [ 301    0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.85      1.00      0.92      1699
           1       0.00      0.00      0.00       301

    accuracy                           0.85      2000
   macro avg       0.42      0.50      0.46      2000
weighted avg       0.72      0.85      0.78      2000

c:\Users\ameen\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ameen\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ameen\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [15]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1699
           1       0.00      0.00      0.00       301

    accuracy                           0.85      2000
   macro avg       0.42      0.50      0.46      2000
weighted avg       0.72      0.85      0.78      2000

c:\Users\ameen\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ameen\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ameen\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [16]:
with open("binary_service_model.pkl","wb")as f:
    pickle.dump(nb_model, f)
with open("binary_model_features.pkl","wb")as f:
    pickle.dump(X.columns.tolist(),f)